spring.application.name=chinanko

# === BASE DE DATOS ===
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === PUERTO INTERNO ===
# Este es el puerto donde escucha Java DENTRO del contenedor
server.port=${PORT:8080}

# === SEGURIDAD ===
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=1000

# === GRAPHQL ===
spring.graphql.graphiql.enabled=true

# ==========================================
# === CONFIGURACIÓN EUREKA CLIENT (RENDER) ===
# ==========================================

# 1. Habilitamos el cliente
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 2. URL del Servidor Eureka (Variable de entorno en Render)
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# 3. Hostname
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false

# ==========================================
# === CORRECCIÓN CRÍTICA DE PUERTOS ===
# ==========================================
# Le decimos a Eureka que, para encontrarnos desde fuera (Gateway),
# use el puerto 80 (HTTP estándar), no el 8080.
# Render recibe la petición en el 80 y la pasa internamente al 8080.
eureka.instance.non-secure-port=80
eureka.instance.non-secure-port-enabled=true
